using TodoApp;

namespace TodoApp.Views;

public partial class TodoPage : ContentPage
{
    public static List<ToDoClass> tasks = new List<ToDoClass>();

    public TodoPage()
    {
        InitializeComponent(); // This method is generated by the XAML compiler

        todoList.ItemsSource = tasks;
    }

    private async void AddTask_Clicked(object sender, EventArgs e)
    {
        await Navigation.PushAsync(new TodoApp.Views.AddTodoPage());
    }
}